name: Shawn Dyer
favicon: null
layout_spectrum: 0.99369
typography_spectrum: 0
title: 'Shawn Dyer | Filmmaker'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3e7bcb'
    - '#715e24'
    - '#001333'
    - '#bca562'
  brandStrength: 0.19215486105531454
  lightness: 0.3563737564254552
  saturation: 0.9846641465555876
  rhythmicContrast: 0.602562882238999
purpose: []
